[2023-03-25T13:58:15.981+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: transform_fact_user.model.dbt_transform_postgres.fact_user manual__2023-03-25T13:58:15.172197+00:00 [queued]>
[2023-03-25T13:58:15.988+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: transform_fact_user.model.dbt_transform_postgres.fact_user manual__2023-03-25T13:58:15.172197+00:00 [queued]>
[2023-03-25T13:58:15.989+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-25T13:58:15.990+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-03-25T13:58:15.991+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-25T13:58:16.001+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): model.dbt_transform_postgres.fact_user> on 2023-03-25 13:58:15.172197+00:00
[2023-03-25T13:58:16.008+0000] {standard_task_runner.py:55} INFO - Started process 137 to run task
[2023-03-25T13:58:16.012+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'transform_fact_user', 'model.dbt_transform_postgres.fact_user', 'manual__2023-03-25T13:58:15.172197+00:00', '--job-id', '85', '--raw', '--subdir', 'DAGS_FOLDER/transform_fact_user.py', '--cfg-path', '/tmp/tmpgk_m0jra']
[2023-03-25T13:58:16.014+0000] {standard_task_runner.py:83} INFO - Job 85: Subtask model.dbt_transform_postgres.fact_user
[2023-03-25T13:58:16.093+0000] {task_command.py:388} INFO - Running <TaskInstance: transform_fact_user.model.dbt_transform_postgres.fact_user manual__2023-03-25T13:58:15.172197+00:00 [running]> on host 677057dd74de
[2023-03-25T13:58:16.154+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=transform_fact_user
AIRFLOW_CTX_TASK_ID=model.dbt_transform_postgres.fact_user
AIRFLOW_CTX_EXECUTION_DATE=2023-03-25T13:58:15.172197+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-25T13:58:15.172197+00:00
[2023-03-25T13:58:16.156+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-03-25T13:58:16.158+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /opt/***/dbt_transform_postgres && dbt run --models fact_user']
[2023-03-25T13:58:16.175+0000] {subprocess.py:86} INFO - Output:
[2023-03-25T13:58:17.538+0000] {subprocess.py:93} INFO - [0m13:58:17  target not specified in profile 'dbt_transform_postgres', using 'default'
[2023-03-25T13:58:17.539+0000] {subprocess.py:93} INFO - [0m13:58:17  Encountered an error while reading profiles:
[2023-03-25T13:58:17.540+0000] {subprocess.py:93} INFO -   ERROR: Runtime Error
[2023-03-25T13:58:17.541+0000] {subprocess.py:93} INFO -   The profile 'dbt_transform_postgres' does not have a target named 'default'. The valid target names for this profile are:
[2023-03-25T13:58:17.542+0000] {subprocess.py:93} INFO -    - dev
[2023-03-25T13:58:17.543+0000] {subprocess.py:93} INFO -    - prodDefined profiles:
[2023-03-25T13:58:17.544+0000] {subprocess.py:93} INFO -  - dbt_transform_postgres
[2023-03-25T13:58:17.545+0000] {subprocess.py:93} INFO - For more information on configuring profiles, please consult the dbt docs:
[2023-03-25T13:58:17.546+0000] {subprocess.py:93} INFO - 
[2023-03-25T13:58:17.547+0000] {subprocess.py:93} INFO - https://docs.getdbt.com/docs/configure-your-profile
[2023-03-25T13:58:17.548+0000] {subprocess.py:93} INFO - 
[2023-03-25T13:58:17.549+0000] {subprocess.py:93} INFO - [0m13:58:17  Encountered an error:
[2023-03-25T13:58:17.551+0000] {subprocess.py:93} INFO - Runtime Error
[2023-03-25T13:58:17.552+0000] {subprocess.py:93} INFO -   Could not run dbt
[2023-03-25T13:58:17.671+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-03-25T13:58:17.686+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-03-25T13:58:17.693+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=transform_fact_user, task_id=model.dbt_transform_postgres.fact_user, execution_date=20230325T135815, start_date=20230325T135815, end_date=20230325T135817
[2023-03-25T13:58:17.707+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 85 for task model.dbt_transform_postgres.fact_user (Bash command failed. The command returned a non-zero exit code 2.; 137)
[2023-03-25T13:58:17.760+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-25T13:58:17.786+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
