[2023-03-25T13:09:34.579+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: transform_fact_user.model.dbt_transform_postgres.fact_user manual__2023-03-25T13:09:33.826158+00:00 [queued]>
[2023-03-25T13:09:34.587+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: transform_fact_user.model.dbt_transform_postgres.fact_user manual__2023-03-25T13:09:33.826158+00:00 [queued]>
[2023-03-25T13:09:34.589+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-25T13:09:34.590+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-03-25T13:09:34.591+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-25T13:09:34.601+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): model.dbt_transform_postgres.fact_user> on 2023-03-25 13:09:33.826158+00:00
[2023-03-25T13:09:34.608+0000] {standard_task_runner.py:55} INFO - Started process 813 to run task
[2023-03-25T13:09:34.611+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'transform_fact_user', 'model.dbt_transform_postgres.fact_user', 'manual__2023-03-25T13:09:33.826158+00:00', '--job-id', '78', '--raw', '--subdir', 'DAGS_FOLDER/transform_fact_user.py', '--cfg-path', '/tmp/tmpbxrb_ziu']
[2023-03-25T13:09:34.613+0000] {standard_task_runner.py:83} INFO - Job 78: Subtask model.dbt_transform_postgres.fact_user
[2023-03-25T13:09:34.686+0000] {task_command.py:388} INFO - Running <TaskInstance: transform_fact_user.model.dbt_transform_postgres.fact_user manual__2023-03-25T13:09:33.826158+00:00 [running]> on host 8b4a0b962415
[2023-03-25T13:09:34.743+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=transform_fact_user
AIRFLOW_CTX_TASK_ID=model.dbt_transform_postgres.fact_user
AIRFLOW_CTX_EXECUTION_DATE=2023-03-25T13:09:33.826158+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-25T13:09:33.826158+00:00
[2023-03-25T13:09:34.746+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-03-25T13:09:34.748+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /opt/***/dbt_transform_postgres && dbt run --models fact_user']
[2023-03-25T13:09:34.765+0000] {subprocess.py:86} INFO - Output:
[2023-03-25T13:09:36.289+0000] {subprocess.py:93} INFO - [0m13:09:36  Encountered an error:
[2023-03-25T13:09:36.293+0000] {subprocess.py:93} INFO - Runtime Error
[2023-03-25T13:09:36.295+0000] {subprocess.py:93} INFO - 
[2023-03-25T13:09:36.296+0000] {subprocess.py:93} INFO -   dbt encountered an error while trying to read your profiles.yml file.
[2023-03-25T13:09:36.297+0000] {subprocess.py:93} INFO - 
[2023-03-25T13:09:36.298+0000] {subprocess.py:93} INFO -   The profiles.yml file at /home/***/.dbt/profiles.yml is empty
[2023-03-25T13:09:36.299+0000] {subprocess.py:93} INFO - 
[2023-03-25T13:09:36.394+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-03-25T13:09:36.408+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-03-25T13:09:36.414+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=transform_fact_user, task_id=model.dbt_transform_postgres.fact_user, execution_date=20230325T130933, start_date=20230325T130934, end_date=20230325T130936
[2023-03-25T13:09:36.432+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 78 for task model.dbt_transform_postgres.fact_user (Bash command failed. The command returned a non-zero exit code 2.; 813)
[2023-03-25T13:09:36.451+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-25T13:09:36.477+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
