[2023-03-05T06:24:28.806+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: airbyte_mongo_postgres_user.airbyte_check_sync manual__2023-03-05T06:24:25.718803+00:00 [queued]>
[2023-03-05T06:24:28.816+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: airbyte_mongo_postgres_user.airbyte_check_sync manual__2023-03-05T06:24:25.718803+00:00 [queued]>
[2023-03-05T06:24:28.817+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-05T06:24:28.818+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-03-05T06:24:28.819+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-05T06:24:28.830+0000] {taskinstance.py:1300} INFO - Executing <Task(AirbyteJobSensor): airbyte_check_sync> on 2023-03-05 06:24:25.718803+00:00
[2023-03-05T06:24:28.836+0000] {standard_task_runner.py:55} INFO - Started process 2317 to run task
[2023-03-05T06:24:28.840+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'airbyte_mongo_postgres_user', 'airbyte_check_sync', 'manual__2023-03-05T06:24:25.718803+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/airbyte_mongo_postgres_user.py', '--cfg-path', '/tmp/tmp7oz60g_b']
[2023-03-05T06:24:28.841+0000] {standard_task_runner.py:83} INFO - Job 34: Subtask airbyte_check_sync
[2023-03-05T06:24:28.918+0000] {task_command.py:388} INFO - Running <TaskInstance: airbyte_mongo_postgres_user.airbyte_check_sync manual__2023-03-05T06:24:25.718803+00:00 [running]> on host 0997e433a2b7
[2023-03-05T06:24:29.023+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=airbyte_mongo_postgres_user
AIRFLOW_CTX_TASK_ID=airbyte_check_sync
AIRFLOW_CTX_EXECUTION_DATE=2023-03-05T06:24:25.718803+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-05T06:24:25.718803+00:00
[2023-03-05T06:24:29.046+0000] {base.py:73} INFO - Using connection ID '***_airbyte_local' for task execution.
[2023-03-05T06:24:29.066+0000] {airbyte.py:72} INFO - Waiting for job 20 to complete.
[2023-03-05T06:25:29.140+0000] {base.py:73} INFO - Using connection ID '***_airbyte_local' for task execution.
[2023-03-05T06:25:29.179+0000] {airbyte.py:72} INFO - Waiting for job 20 to complete.
[2023-03-05T06:26:29.227+0000] {base.py:73} INFO - Using connection ID '***_airbyte_local' for task execution.
[2023-03-05T06:26:29.258+0000] {airbyte.py:72} INFO - Waiting for job 20 to complete.
[2023-03-05T06:27:29.328+0000] {base.py:73} INFO - Using connection ID '***_airbyte_local' for task execution.
[2023-03-05T06:27:29.348+0000] {airbyte.py:72} INFO - Waiting for job 20 to complete.
[2023-03-05T06:28:29.422+0000] {base.py:73} INFO - Using connection ID '***_airbyte_local' for task execution.
[2023-03-05T06:28:29.467+0000] {airbyte.py:72} INFO - Waiting for job 20 to complete.
[2023-03-05T06:29:29.524+0000] {base.py:73} INFO - Using connection ID '***_airbyte_local' for task execution.
[2023-03-05T06:29:29.557+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 199, in execute
    poke_return = self.poke(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/airbyte/sensors/airbyte.py", line 63, in poke
    raise AirflowException(f"Job failed: \n{job}")
airflow.exceptions.AirflowException: Job failed: 
<Response [200]>
[2023-03-05T06:29:29.563+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=airbyte_mongo_postgres_user, task_id=airbyte_check_sync, execution_date=20230305T062425, start_date=20230305T062428, end_date=20230305T062929
[2023-03-05T06:29:29.578+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 34 for task airbyte_check_sync (Job failed: 
<Response [200]>; 2317)
[2023-03-05T06:29:29.625+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-05T06:29:29.644+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
