[2023-03-25T13:45:37.831+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: transform_fact_user.model.dbt_transform_postgres.fact_user manual__2023-03-25T13:45:36.930427+00:00 [queued]>
[2023-03-25T13:45:37.838+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: transform_fact_user.model.dbt_transform_postgres.fact_user manual__2023-03-25T13:45:36.930427+00:00 [queued]>
[2023-03-25T13:45:37.840+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-25T13:45:37.841+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-03-25T13:45:37.842+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-25T13:45:37.852+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): model.dbt_transform_postgres.fact_user> on 2023-03-25 13:45:36.930427+00:00
[2023-03-25T13:45:37.859+0000] {standard_task_runner.py:55} INFO - Started process 1577 to run task
[2023-03-25T13:45:37.864+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'transform_fact_user', 'model.dbt_transform_postgres.fact_user', 'manual__2023-03-25T13:45:36.930427+00:00', '--job-id', '82', '--raw', '--subdir', 'DAGS_FOLDER/transform_fact_user.py', '--cfg-path', '/tmp/tmp3qq5or2f']
[2023-03-25T13:45:37.866+0000] {standard_task_runner.py:83} INFO - Job 82: Subtask model.dbt_transform_postgres.fact_user
[2023-03-25T13:45:37.943+0000] {task_command.py:388} INFO - Running <TaskInstance: transform_fact_user.model.dbt_transform_postgres.fact_user manual__2023-03-25T13:45:36.930427+00:00 [running]> on host 677057dd74de
[2023-03-25T13:45:38.007+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=transform_fact_user
AIRFLOW_CTX_TASK_ID=model.dbt_transform_postgres.fact_user
AIRFLOW_CTX_EXECUTION_DATE=2023-03-25T13:45:36.930427+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-25T13:45:36.930427+00:00
[2023-03-25T13:45:38.009+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-03-25T13:45:38.015+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /opt/***/dbt_transform_postgres && dbt run --models fact_user']
[2023-03-25T13:45:38.032+0000] {subprocess.py:86} INFO - Output:
[2023-03-25T13:45:39.429+0000] {subprocess.py:93} INFO - [0m13:45:39  Encountered an error:
[2023-03-25T13:45:39.431+0000] {subprocess.py:93} INFO - Runtime Error
[2023-03-25T13:45:39.432+0000] {subprocess.py:93} INFO -   Syntax error near line 33
[2023-03-25T13:45:39.433+0000] {subprocess.py:93} INFO -   ------------------------------
[2023-03-25T13:45:39.434+0000] {subprocess.py:93} INFO -   30 | # In this example config, we tell dbt to build all models in the example/
[2023-03-25T13:45:39.436+0000] {subprocess.py:93} INFO -   31 | # directory as views. These settings can be overridden in the individual model
[2023-03-25T13:45:39.437+0000] {subprocess.py:93} INFO -   32 | # files using the `{{ config(...) }}` macro.
[2023-03-25T13:45:39.438+0000] {subprocess.py:93} INFO -   33 |  models:
[2023-03-25T13:45:39.440+0000] {subprocess.py:93} INFO -   34 |   dbt_transform_postgres:
[2023-03-25T13:45:39.441+0000] {subprocess.py:93} INFO -   35 |     # Config indicated by + and applies to all files under models/example/
[2023-03-25T13:45:39.442+0000] {subprocess.py:93} INFO -   36 |     +materialized: table
[2023-03-25T13:45:39.443+0000] {subprocess.py:93} INFO - 
[2023-03-25T13:45:39.444+0000] {subprocess.py:93} INFO -   Raw Error:
[2023-03-25T13:45:39.445+0000] {subprocess.py:93} INFO -   ------------------------------
[2023-03-25T13:45:39.446+0000] {subprocess.py:93} INFO -   while parsing a block mapping
[2023-03-25T13:45:39.447+0000] {subprocess.py:93} INFO -     in "<unicode string>", line 4, column 1
[2023-03-25T13:45:39.448+0000] {subprocess.py:93} INFO -   did not find expected key
[2023-03-25T13:45:39.449+0000] {subprocess.py:93} INFO -     in "<unicode string>", line 33, column 2
[2023-03-25T13:45:39.532+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-03-25T13:45:39.546+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-03-25T13:45:39.551+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=transform_fact_user, task_id=model.dbt_transform_postgres.fact_user, execution_date=20230325T134536, start_date=20230325T134537, end_date=20230325T134539
[2023-03-25T13:45:39.562+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 82 for task model.dbt_transform_postgres.fact_user (Bash command failed. The command returned a non-zero exit code 2.; 1577)
[2023-03-25T13:45:39.588+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-25T13:45:39.615+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
