[2023-03-05T14:41:08.837+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: transform_fact_user.model.dbt_transform_postgres.fact_user manual__2023-03-05T14:41:08.097814+00:00 [queued]>
[2023-03-05T14:41:08.854+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: transform_fact_user.model.dbt_transform_postgres.fact_user manual__2023-03-05T14:41:08.097814+00:00 [queued]>
[2023-03-05T14:41:08.856+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-05T14:41:08.858+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-03-05T14:41:08.859+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-05T14:41:08.871+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): model.dbt_transform_postgres.fact_user> on 2023-03-05 14:41:08.097814+00:00
[2023-03-05T14:41:08.881+0000] {standard_task_runner.py:55} INFO - Started process 1056 to run task
[2023-03-05T14:41:08.887+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'transform_fact_user', 'model.dbt_transform_postgres.fact_user', 'manual__2023-03-05T14:41:08.097814+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/transform_fact_user.py', '--cfg-path', '/tmp/tmpxrlrwi9p']
[2023-03-05T14:41:08.889+0000] {standard_task_runner.py:83} INFO - Job 54: Subtask model.dbt_transform_postgres.fact_user
[2023-03-05T14:41:09.014+0000] {task_command.py:388} INFO - Running <TaskInstance: transform_fact_user.model.dbt_transform_postgres.fact_user manual__2023-03-05T14:41:08.097814+00:00 [running]> on host 02e1ac09fd08
[2023-03-05T14:41:09.097+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=transform_fact_user
AIRFLOW_CTX_TASK_ID=model.dbt_transform_postgres.fact_user
AIRFLOW_CTX_EXECUTION_DATE=2023-03-05T14:41:08.097814+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-05T14:41:08.097814+00:00
[2023-03-05T14:41:09.100+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-03-05T14:41:09.102+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd dbt_transform_postgres && dbt run --models fact_user']
[2023-03-05T14:41:09.120+0000] {subprocess.py:86} INFO - Output:
[2023-03-05T14:41:09.125+0000] {subprocess.py:93} INFO - /bin/bash: line 1: cd: dbt_transform_postgres: No such file or directory
[2023-03-05T14:41:09.127+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-03-05T14:41:09.139+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-03-05T14:41:09.146+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=transform_fact_user, task_id=model.dbt_transform_postgres.fact_user, execution_date=20230305T144108, start_date=20230305T144108, end_date=20230305T144109
[2023-03-05T14:41:09.164+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 54 for task model.dbt_transform_postgres.fact_user (Bash command failed. The command returned a non-zero exit code 1.; 1056)
[2023-03-05T14:41:09.225+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-05T14:41:09.255+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
