[2023-03-26T09:27:32.860+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: ge_t_postgres_fact_user.set_up_source manual__2023-03-26T09:27:30.118437+00:00 [queued]>
[2023-03-26T09:27:32.869+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: ge_t_postgres_fact_user.set_up_source manual__2023-03-26T09:27:30.118437+00:00 [queued]>
[2023-03-26T09:27:32.871+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-26T09:27:32.872+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-03-26T09:27:32.874+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-26T09:27:32.887+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): set_up_source> on 2023-03-26 09:27:30.118437+00:00
[2023-03-26T09:27:32.898+0000] {standard_task_runner.py:55} INFO - Started process 1166 to run task
[2023-03-26T09:27:32.902+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'ge_t_postgres_fact_user', 'set_up_source', 'manual__2023-03-26T09:27:30.118437+00:00', '--job-id', '141', '--raw', '--subdir', 'DAGS_FOLDER/ge_t_postgres_fact_user.py', '--cfg-path', '/tmp/tmphrpb7dtv']
[2023-03-26T09:27:32.904+0000] {standard_task_runner.py:83} INFO - Job 141: Subtask set_up_source
[2023-03-26T09:27:32.976+0000] {task_command.py:388} INFO - Running <TaskInstance: ge_t_postgres_fact_user.set_up_source manual__2023-03-26T09:27:30.118437+00:00 [running]> on host 07b54bb2b8de
[2023-03-26T09:27:33.033+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ge_t_postgres_fact_user
AIRFLOW_CTX_TASK_ID=set_up_source
AIRFLOW_CTX_EXECUTION_DATE=2023-03-26T09:27:30.118437+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-26T09:27:30.118437+00:00
[2023-03-26T09:27:33.036+0000] {util.py:1938} INFO - Could not find local context root directory
[2023-03-26T09:27:33.038+0000] {base.py:2129} INFO - Created temporary directory '/tmp/tmpco7x7o8h' for ephemeral docs site
[2023-03-26T09:27:33.041+0000] {abstract_data_context.py:5425} INFO - EphemeralDataContext has not implemented `_load_fluent_config()` returning empty `GxConfig`
[2023-03-26T09:27:33.042+0000] {config.py:91} INFO - Loading 'datasources' ->
{}
[2023-03-26T09:27:33.043+0000] {config.py:149} INFO - Loaded 'datasources' ->
{}
[2023-03-26T09:27:34.064+0000] {logging_mixin.py:137} INFO - [{'name': 'postgres_aws', 'execution_engine': {'class_name': 'SqlAlchemyExecutionEngine', 'credentials': {'host': '13.229.110.215', 'port': '5432', 'username': 'vu_ngo', 'password': 1993, 'database': 'vu_ngo', 'drivername': 'postgresql'}, 'module_name': 'great_expectations.execution_engine'}, 'class_name': 'Datasource', 'module_name': 'great_expectations.datasource', 'data_connectors': {'default_runtime_data_connector_name': {'batch_identifiers': ['default_identifier_name'], 'class_name': 'RuntimeDataConnector', 'module_name': 'great_expectations.datasource.data_connector'}, 'default_inferred_data_connector_name': {'class_name': 'InferredAssetSqlDataConnector', 'introspection_directives': {'schema_name': 'public'}, 'include_schema_name': True, 'module_name': 'great_expectations.datasource.data_connector'}, 'default_configured_data_connector_name': {'class_name': 'ConfiguredAssetSqlDataConnector', 'module_name': 'great_expectations.datasource.data_connector', 'assets': {'fact_user': {'schema_name': 'public', 'class_name': 'Asset', 'module_name': 'great_expectations.datasource.data_connector.asset'}}}}}]
[2023-03-26T09:27:34.068+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-03-26T09:27:34.106+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=ge_t_postgres_fact_user, task_id=set_up_source, execution_date=20230326T092730, start_date=20230326T092732, end_date=20230326T092734
[2023-03-26T09:27:34.140+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2023-03-26T09:27:34.161+0000] {taskinstance.py:2578} INFO - 1 downstream tasks scheduled from follow-on schedule check
