[2023-03-05T11:40:16.663+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: transform_fact_user.task_2 manual__2023-03-05T11:40:14.899854+00:00 [queued]>
[2023-03-05T11:40:16.670+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: transform_fact_user.task_2 manual__2023-03-05T11:40:14.899854+00:00 [queued]>
[2023-03-05T11:40:16.671+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-05T11:40:16.672+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-03-05T11:40:16.673+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-05T11:40:16.685+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): task_2> on 2023-03-05 11:40:14.899854+00:00
[2023-03-05T11:40:16.692+0000] {standard_task_runner.py:55} INFO - Started process 2664 to run task
[2023-03-05T11:40:16.696+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'transform_fact_user', 'task_2', 'manual__2023-03-05T11:40:14.899854+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/transform_fact_user.py', '--cfg-path', '/tmp/tmp8c6l7h1p']
[2023-03-05T11:40:16.697+0000] {standard_task_runner.py:83} INFO - Job 43: Subtask task_2
[2023-03-05T11:40:16.770+0000] {task_command.py:388} INFO - Running <TaskInstance: transform_fact_user.task_2 manual__2023-03-05T11:40:14.899854+00:00 [running]> on host 0997e433a2b7
[2023-03-05T11:40:16.828+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=transform_fact_user
AIRFLOW_CTX_TASK_ID=task_2
AIRFLOW_CTX_EXECUTION_DATE=2023-03-05T11:40:14.899854+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-05T11:40:14.899854+00:00
[2023-03-05T11:40:16.829+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-03-05T11:40:16.830+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'ls home\x07irflow']
[2023-03-05T11:40:16.843+0000] {subprocess.py:86} INFO - Output:
[2023-03-05T11:40:16.848+0000] {subprocess.py:93} INFO - ls: cannot access 'home'$'\a''irflow': No such file or directory
[2023-03-05T11:40:16.849+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-03-05T11:40:16.861+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-03-05T11:40:16.865+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=transform_fact_user, task_id=task_2, execution_date=20230305T114014, start_date=20230305T114016, end_date=20230305T114016
[2023-03-05T11:40:16.875+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 43 for task task_2 (Bash command failed. The command returned a non-zero exit code 2.; 2664)
[2023-03-05T11:40:16.909+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-05T11:40:16.926+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
