[2023-03-26T10:09:50.301+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: ge_t_postgres_fact_user.set_up_source manual__2023-03-26T10:09:47.318823+00:00 [queued]>
[2023-03-26T10:09:50.308+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: ge_t_postgres_fact_user.set_up_source manual__2023-03-26T10:09:47.318823+00:00 [queued]>
[2023-03-26T10:09:50.310+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-26T10:09:50.311+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-03-26T10:09:50.312+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-26T10:09:50.327+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): set_up_source> on 2023-03-26 10:09:47.318823+00:00
[2023-03-26T10:09:50.337+0000] {standard_task_runner.py:55} INFO - Started process 94 to run task
[2023-03-26T10:09:50.342+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'ge_t_postgres_fact_user', 'set_up_source', 'manual__2023-03-26T10:09:47.318823+00:00', '--job-id', '149', '--raw', '--subdir', 'DAGS_FOLDER/ge_t_postgres_fact_user.py', '--cfg-path', '/tmp/tmp3ursn8xt']
[2023-03-26T10:09:50.344+0000] {standard_task_runner.py:83} INFO - Job 149: Subtask set_up_source
[2023-03-26T10:09:50.450+0000] {task_command.py:388} INFO - Running <TaskInstance: ge_t_postgres_fact_user.set_up_source manual__2023-03-26T10:09:47.318823+00:00 [running]> on host 6feacf63da28
[2023-03-26T10:09:50.522+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ge_t_postgres_fact_user
AIRFLOW_CTX_TASK_ID=set_up_source
AIRFLOW_CTX_EXECUTION_DATE=2023-03-26T10:09:47.318823+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-26T10:09:47.318823+00:00
[2023-03-26T10:09:50.545+0000] {file_data_context.py:163} INFO - FileDataContext loading fluent config
[2023-03-26T10:09:50.555+0000] {config.py:173} INFO - GxConfig.parse_yaml() failed with errors - [{'loc': ('fluent_datasources',), 'msg': 'field required', 'type': 'value_error.missing'}]
[2023-03-26T10:09:50.557+0000] {config.py:177} INFO - GxConfig.parse_yaml() returning empty `fluent_datasources`
[2023-03-26T10:09:50.558+0000] {config.py:91} INFO - Loading 'datasources' ->
{}
[2023-03-26T10:09:50.560+0000] {config.py:149} INFO - Loaded 'datasources' ->
{}
[2023-03-26T10:09:51.748+0000] {logging_mixin.py:137} INFO - [{'name': 'postgres_aws_1', 'module_name': 'great_expectations.datasource', 'execution_engine': {'module_name': 'great_expectations.execution_engine', 'class_name': 'SqlAlchemyExecutionEngine', 'credentials': {'host': '13.229.110.215', 'port': '5432', 'username': 'vu_ngo', 'password': 1993, 'database': 'vu_ngo', 'drivername': 'postgresql'}}, 'class_name': 'Datasource', 'data_connectors': {'default_runtime_data_connector_name': {'module_name': 'great_expectations.datasource.data_connector', 'batch_identifiers': ['default_identifier_name'], 'class_name': 'RuntimeDataConnector'}, 'default_inferred_data_connector_name': {'module_name': 'great_expectations.datasource.data_connector', 'class_name': 'InferredAssetSqlDataConnector', 'include_schema_name': True, 'introspection_directives': {'schema_name': 'public'}}, 'default_configured_data_connector_name': {'module_name': 'great_expectations.datasource.data_connector', 'assets': {'fact_user': {'module_name': 'great_expectations.datasource.data_connector.asset', 'class_name': 'Asset', 'schema_name': 'public'}}, 'class_name': 'ConfiguredAssetSqlDataConnector'}}}]
[2023-03-26T10:09:51.757+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-03-26T10:09:51.819+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=ge_t_postgres_fact_user, task_id=set_up_source, execution_date=20230326T100947, start_date=20230326T100950, end_date=20230326T100951
[2023-03-26T10:09:51.886+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2023-03-26T10:09:51.914+0000] {taskinstance.py:2578} INFO - 1 downstream tasks scheduled from follow-on schedule check
